### PR TITLE
fix: Make DB save actions thread safe

### LINKED ISSUE #62: DB operations are being done in parallel
Discovered some time ago, DB operations seem to not be working in parallel/async.

Discord_z0XYjCFwSv

### PR DESCRIPTION
**Pull request by Nekromateion**
Use a lock to prevent exceptions from saving the DB on multiple threads.
Closes #62

### CODE REVIEW

**Review by regalialong — COMMENTED** [review]
Okay, so as discussed in IM, this will work but I'm worried about congestion from multiple pieces of content waiting on a lock, so I'd personally like to explore alternative ways of fixing this.

**Review by DubyaDude — APPROVED** [review]
While not ideal, it's best to get 3.x in a stable state since other proposed solutions would require some refactor.

**Comment by DubyaDude** [comment]
@regalialong I think you're exaggerating it 'backing up' because of the locks. From the way things are written, saves happen right before return. The only thing really being 'backed up' is just the parallel completing, which is perfectly fine for our use case.

**Comment by regalialong** [comment]
I'm saying this because it's already a little worrying that we're timing out on database operations which would otherwise retry if I understand correctly, but sure, since this works, let's just do this for now.

**Review by regalialong — APPROVED** [review]

**Pull request merged**
