### PR TITLE
Experiment: Version Aware Indexer

### LINKED ISSUE #6: File deletions aren't handled
If you clear your cache and run AdGoBye, it'll still attempt to run all plugins with old cache'd files.

### LINKED ISSUE #9: Plugin Interface is not fully implemented on AGB side
https://github.com/AdGoBye/AdGoBye/blob/378c22c9baeb505200d8d2d27a78fff885d6aa4d/AdGoBye.Plugins/IPlugin.cs#L15-L23
https://github.com/AdGoBye/AdGoBye/blob/378c22c9baeb505200d8d2d27a78fff885d6aa4d/AdGoBye.Plugins/IPlugin.cs#L34-L37

We don't actually use these during patching operations even though IPlugin specifies their existence.

### PR DESCRIPTION
**Pull request by regalialong**
This branch contains an experimental refactor to the Indexer component, which uses the version resolved from the directory name to skip expensive AT parsing and tracks what component (Plugin name, `Blocklists`) modified a piece of content.

This is part of a transition to make the Index less transient and improve reliability.

Closes #9
Closes #6 
Implements #7

### CODE REVIEW

**Comment by regalialong** [comment]
Foundation is slowly coming together, I need to clean up this code though.

**Comment by regalialong** [comment]
@DubyaDude Hey, you've been working from time to time on AGB and plucking some mistakes of mine. You want to take a look at this branch?

I've been trying to make the Index more reliable by actually walking the file system for the expected structure and adjusting based on that, this should be workable as-is (although this probably needs a few tweaks performance wise, Rider is screaming)

The Index is stored in SQLite per EF instead which hopefully should be more reliable than the Json index, this could be split off into its own `State` component if we ever need to keep track of more things.

I'll probably publish a test build of this at some point for stress testing after I get to the bottom of the `Cannot access a closed file.` issue.

**Review by DubyaDude — APPROVED** [review]
I don't see any glaring issues off a quick read.
Definitely should do a release of the current master before pulling this in case a rollback is needed.

**Comment by regalialong** [comment]
Threw it at my 64GiB cache copy, parsed files without problems. I'll go publish a pre-release.

**Comment by regalialong** [comment]
https://github.com/AdGoBye/AdGoBye/discussions/17

**Comment by DubyaDude** [comment]
I still would recommend making a 1.X stable release, which I've had to hand out my compile of much more than I'd like.

**Comment by regalialong** [comment]
I'd be fine with that, although, this branch has been open for way longer than I like. It should have been merged into main the moment it started conflicting, so I really want to get this into main as soon as I know it's not demonstrably broken (unlike how [2bc564a](https://github.com/AdGoBye/AdGoBye/releases/tag/v2.0.0-beta%2B2bc564a) was).

**Comment by regalialong** [comment]
I really don't like how long this branch has been alive, has v1.2.0 been stable enough for users that we can move v2 into main?

**Comment by DubyaDude** [comment]
The only issue I've seen a handful of times that got reported is the duplicate content id existing on occasion, If we add error handling for that I think v2 is good to go.

**Comment by regalialong** [comment]
Okay, just validated that world conflict resolution should in theory work. If the artifacts from c7d4178 work, I'd really want this branch in main.

**Review by DubyaDude — APPROVED** [review]
LGTM, had it thrown at a few caches and there don't seem to be any issues.
No initial issues. When do you plan to make the release?

**Comment by regalialong** [comment]
Repeating what I said in voice call for transparency, I have some changes stashed that I'd like to apply (as well as maybe refactoring the components here). I'll consider a release then, until now, the artifacts are effectively releases without the ceremony.

**Pull request merged**
