### PR TITLE
 Add patch failure error handling for Version 2

### PR DESCRIPTION
**Pull request by DubyaDude**
Add same error patch handling referenced in #15 for version 2.

### CODE REVIEW

**Comment by DubyaDude** [comment]
may not be needed, mightve misheard issue

**Comment by regalialong** [comment]
I'll look at this once I'm free, a little bit of patience please.

**Review by regalialong — COMMENTED** [review]
Looks fine to me, what's the change to draft for?

**Comment by DubyaDude** [comment]
> Looks fine to me, what's the change to draft for?

Out of draft now

**Pull request merged**
