### PR TITLE
Split Settings into subcategories

### LINKED ISSUE #70: Split Settings into subcategories
[We have a good amount of Settings now](https://github.com/AdGoBye/AdGoBye/blob/281640108ebeccd6d77b888520cf324ed24ce98b/AdGoBye/appsettings.json), we should subcategorize them (probably by Class) to make it more obvious which Setting is responsible for what.

### PR DESCRIPTION
**Pull request by Nekromateion**
Split settings into subcategories and create a basic automatic conversion for old configs.

Closes #70

### CODE REVIEW

**Comment by DubyaDude** [comment]
Build failed?

**Comment by Nekromateion** [comment]
Unsure why.

**Comment by DubyaDude** [comment]
as said in build logs: 

`Error: /home/runner/work/AdGoBye/AdGoBye/AdGoBye/Blocklist.cs(254,34): error CS1061: 'Settings.SettingsOptionsV2' does not contain a definition for 'SendUnmatchedObjectsToDevs' and no accessible extension method 'SendUnmatchedObjectsToDevs' accepting a first argument of type 'Settings.SettingsOptionsV2' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/AdGoBye/AdGoBye/AdGoBye/AdGoBye.csproj]`

**Review by DubyaDude — APPROVED** [review]

**Comment by regalialong** [comment]
Okay, I think I'd be good with signing this off in this state.

**Review by DubyaDude — APPROVED** [review]

**Comment by regalialong** [comment]
Once again, thank you very much for the help.

**Pull request merged**
