### PR TITLE
Parallel indexing

### LINKED ISSUE #11: Deadlock of Hell
a7684660b5fe801e3d096e1555cfe075f5c57620
ce7bed40a57a43f90417c8eec78483a1c05e9576

There have been repeated instances where a shared static `Serilog.ILogger` instance caused the code to halt if it was parallelized per `Parallel.ForEach`. After either removing the comment, logging per the static global `Log.Logger`, or giving every thread its own logger instance like ce7bed40a57a43f90417c8eec78483a1c05e9576 did, the code works again.

Debugger gets stuck on Logger.Warning

This is nearing showstopper since it either requires:
- not contextually logging whenever a method is parallelized (which we may not have control [due to Plugins] if we decide to parallelize patching and can quickly become viral)
- not contextually logging (which makes the logs less useful since it helps knowing what component is logging)
- not parallelizing (which would likely have a performance impact)

All three of these are varying amounts of undesirable.

### PR DESCRIPTION
**Pull request by DubyaDude**
With the v2 rewrite, I can no longer recreate the deadlock of hell issue. This seems to confirm my suspicion that the stack in which that parallel was started caused some extremely niche issues.

Attempting to re-add parallelization to the indexing process.

- Closes #11

### CODE REVIEW

**Comment by regalialong** [comment]
Threw this at my 64GiB cache folder for testing, it went through that pretty fast and didn't break so looks good to me.

**Review by regalialong — APPROVED** [review]
No problems with this on a technichal site, I might restructure / rename this at some point but that's cosmetic.

**Comment by DubyaDude** [comment]
Few people have been running this, and haven't run into any issues with this implementation

**Comment by regalialong** [comment]
Good enough for me, we can revert it worst case

**Pull request merged**
