### PR TITLE
fix(Live): Fix preventing deletion of log file

### PR DESCRIPTION
**Pull request by DubyaDude**
- Fix prevention of log deletion file.

### CODE REVIEW

**Review by regalialong — COMMENTED** [review]
What is this meant to address?

Unrelated: You should probably force push this to fix the grammar mistake in your commit message.

**Comment by Myrkie** [comment]
> What is this meant to address?
> 
> Unrelated: You should probably force push this to fix the grammar mistake in your commit message.

AGB will prevent vrchat from cleaning up previous output log files, which will break writing to log completely, vrchat being unable to delete them so it also fails to create a new one.

**Comment by regalialong** [comment]
Ah, I assumed we weren't holding _any_ sorts of locks.
How does AGB handle the live deletion? Is this code enough or do we need to handle it?

**Review by regalialong — APPROVED** [review]
It handles it fine, I'll go ahead and fix the commit message.

**Comment by regalialong** [comment]
Actually, fixing the commit message from here is a bit annoying due to the main merge so I'll just push this straight to main with a co-author.

**Pull request closed without merging**
